name = "capcut-backend"
main = "src/index.js"
compatibility_date = "2024-11-29"

[[d1_databases]]
binding = "DB"
database_name = "capcut_comments"
database_id = "18ba4a7c-fb04-40c4-bb0a-9860cc2d40a5"

# Run every 72 hours (at 00:00 UTC on day 1, 4, 7, 10...)
[triggers]
crons = ["0 0 */3 * *"]
